_: {
  imports = [
    ./bufferline.nix
    ./catppuccin.nix
    ./cmp-cmdline.nix
    ./cmp.nix
    ./colorizer.nix
    ./comment.nix
    ./conform.nix
    ./crates-nvim.nix
    ./flutter-tools.nix
    ./gitsigns.nix
    ./illuminate.nix
    ./indent-blankline.nix
    ./lsp.nix
    ./lspsaga.nix
    ./lualine.nix
    ./markdown-preview.nix
    ./mini.nix
    ./neogit.nix
    ./noice.nix
    ./none-ls.nix
    ./notify.nix
    ./nvim-autopairs.nix
    ./rzip.nix
    ./telescope.nix
    ./treesitter.nix
    ./trim.nix
    ./trouble.nix
    ./ts-autotag.nix
    ./wakatime.nix
    ./web-devicons.nix
  ];
}
